/**
 * Provider display metadata (name, brand color) generated from
 * reference/9router/open-sse/providers/registry. Pure — no vscode imports.
 */
export interface ProviderMeta {
  name: string;
  color: string;
  textIcon?: string;
  /** false when the provider serves no LLM (TTS, search, …). */
  llm?: boolean;
  /** Free providers that need no account (always shown in the topology). */
  freeNoAuth?: boolean;
}

export const PROVIDER_META: Record<string, ProviderMeta> = {
  "agnes": { name: "Agnes AI", color: "#7C3AED", textIcon: "AG" },
  "alicode": { name: "Alibaba", color: "#FF6A00", textIcon: "ALi" },
  "alicode-intl": { name: "Alibaba Coding", color: "#FF6A00", textIcon: "ALi" },
  "alims-intl": { name: "Alibaba Studio", color: "#FF6A00", textIcon: "ALi" },
  "alitp-intl": { name: "Alibaba Token Plan", color: "#FF6A00", textIcon: "ATP" },
  "anthropic": { name: "Anthropic", color: "#D97757", textIcon: "AN" },
  "antigravity": { name: "Antigravity", color: "#F59E0B" },
  "api-airforce": { name: "API.airforce", color: "#0EA5E9", textIcon: "AF" },
  "assemblyai": { name: "AssemblyAI", color: "#0062FF", textIcon: "AA", llm: false },
  "atria": { name: "Atria Dawn", color: "#C2410C", textIcon: "AD" },
  "aws-polly": { name: "AWS Polly", color: "#FF9900", textIcon: "PL", llm: false },
  "azure": { name: "Azure OpenAI", color: "#0078D4", textIcon: "AZ" },
  "bai": { name: "B.AI", color: "#0369A1", textIcon: "BA" },
  "baidu": { name: "Baidu Qianfan", color: "#2932E1", textIcon: "BD" },
  "bazaarlink": { name: "Bazaarlink", color: "#DC2626", textIcon: "BZ" },
  "black-forest-labs": { name: "Black Forest Labs", color: "#111827", textIcon: "BF", llm: false },
  "blackbox": { name: "Blackbox AI", color: "#5B5FEF", textIcon: "BB" },
  "bluesminds": { name: "BluesMinds", color: "#2563EB", textIcon: "BM" },
  "brave-search": { name: "Brave Search", color: "#FB542B", textIcon: "BR", llm: false },
  "byteplus": { name: "BytePlus ModelArk", color: "#2563EB", textIcon: "BP" },
  "cartesia": { name: "Cartesia", color: "#FF4F8B", textIcon: "CA", llm: false },
  "cerebras": { name: "Cerebras", color: "#FF4F00", textIcon: "CB" },
  "chutes": { name: "Chutes AI", color: "#ffffffff", textIcon: "CH" },
  "claude": { name: "Claude Code", color: "#D97757" },
  "cline": { name: "Cline", color: "#5B9BD5", textIcon: "CL" },
  "clinepass": { name: "ClinePass", color: "#5B9BD5", textIcon: "CP" },
  "cloudflare-ai": { name: "Cloudflare", color: "#F38020", textIcon: "CF" },
  "codebuddy-cn": { name: "CodeBuddy CN", color: "#006EFF" },
  "codebuddy-intl": { name: "CodeBuddy", color: "#006EFF" },
  "codex": { name: "OpenAI Codex", color: "#3B82F6" },
  "cohere": { name: "Cohere", color: "#39594D", textIcon: "CO" },
  "comfyui": { name: "ComfyUI", color: "#4CAF50", textIcon: "CF", llm: false },
  "commandcode": { name: "Command Code", color: "#000000", textIcon: "CC" },
  "coqui": { name: "Coqui TTS", color: "#10B981", textIcon: "CQ", llm: false },
  "cursor": { name: "Cursor IDE", color: "#00D4AA" },
  "dahl": { name: "Dahl Inference", color: "#1E40AF", textIcon: "DH" },
  "deepgram": { name: "Deepgram", color: "#13EF93", textIcon: "DG", llm: false },
  "deepseek": { name: "DeepSeek", color: "#4D6BFE", textIcon: "DS" },
  "devin-cli": { name: "Devin CLI", color: "#6366F1", textIcon: "DV", freeNoAuth: true },
  "edge-tts": { name: "Edge TTS", color: "#0078D4", textIcon: "ET", llm: false },
  "elevenlabs": { name: "ElevenLabs", color: "#6C47FF", textIcon: "EL", llm: false },
  "exa": { name: "Exa", color: "#2563EB", textIcon: "EX", llm: false },
  "fal-ai": { name: "Fal.ai", color: "#2563EB", textIcon: "FL", llm: false },
  "featherless": { name: "Featherless", color: "#111827", textIcon: "FL" },
  "firecrawl": { name: "Firecrawl", color: "#F59E0B", textIcon: "FC", llm: false },
  "fireworks": { name: "Fireworks AI", color: "#7B2EF2", textIcon: "FW" },
  "fish-audio": { name: "Fish Audio", color: "#1E9BF0", textIcon: "FA", llm: false },
  "gemini": { name: "Gemini", color: "#4285F4", textIcon: "GE" },
  "gemini-cli": { name: "Gemini CLI", color: "#4285F4" },
  "github": { name: "GitHub Copilot", color: "#333333" },
  "gitlab": { name: "GitLab Duo", color: "#FC6D26", textIcon: "GL" },
  "glm": { name: "GLM Coding", color: "#2563EB", textIcon: "GL" },
  "glm-cn": { name: "GLM (China)", color: "#DC2626", textIcon: "GC" },
  "google-pse": { name: "Google PSE", color: "#4285F4", textIcon: "GP", llm: false },
  "google-tts": { name: "Google TTS", color: "#4285F4", textIcon: "GT", llm: false },
  "grok-cli": { name: "Grok CLI (Grok Build)", color: "#1DA1F2", textIcon: "GC" },
  "grok-web": { name: "Grok Web (Subscription)", color: "#1DA1F2", textIcon: "GW" },
  "groq": { name: "Groq", color: "#F55036", textIcon: "GQ" },
  "huggingface": { name: "HuggingFace", color: "#FFD21E", textIcon: "HF", llm: false },
  "hyperbolic": { name: "Hyperbolic", color: "#00D4FF", textIcon: "HY" },
  "iflow": { name: "iFlow AI", color: "#6366F1" },
  "inworld": { name: "Inworld TTS", color: "#FF6B6B", textIcon: "IW", llm: false },
  "jina-ai": { name: "Jina AI", color: "#2563EB", textIcon: "JA", llm: false },
  "jina-reader": { name: "Jina Reader", color: "#000000", textIcon: "JR", llm: false },
  "kilo-gateway": { name: "Kilo Gateway", color: "#8B5CF6", textIcon: "KG" },
  "kilocode": { name: "Kilo Code", color: "#FF6B35", textIcon: "KC" },
  "kimchi": { name: "Kimchi", color: "#FF521D", textIcon: "KC" },
  "kimi": { name: "Kimi", color: "#1E3A8A", textIcon: "KM" },
  "kiro": { name: "Kiro AI", color: "#FF6B35" },
  "linkup": { name: "Linkup", color: "#0EA5E9", textIcon: "LK", llm: false },
  "llm7": { name: "LLM7", color: "#7C3AED", textIcon: "L7" },
  "local-device": { name: "Local Device", color: "#64748B", textIcon: "LD", llm: false },
  "mimo-free": { name: "MiMo Code Free", color: "#FF6900", textIcon: "MF", freeNoAuth: true },
  "minimax": { name: "Minimax Coding", color: "#7C3AED", textIcon: "MM" },
  "minimax-cn": { name: "Minimax (China)", color: "#DC2626", textIcon: "MC" },
  "mistral": { name: "Mistral", color: "#FF7000", textIcon: "MI" },
  "mmf": { name: "MMF", color: "#6366F1", textIcon: "MF" },
  "morph": { name: "Morph", color: "#14B8A6", textIcon: "MP" },
  "nanobanana": { name: "NanoBanana API", color: "#FFD700", textIcon: "🍌", llm: false },
  "nebius": { name: "Nebius AI", color: "#6C5CE7", textIcon: "NB" },
  "nvidia": { name: "NVIDIA NIM", color: "#76B900", textIcon: "NV" },
  "ollama": { name: "Ollama Cloud", color: "#ffffffff", textIcon: "OL" },
  "ollama-local": { name: "Ollama Local", color: "#ffffffff", textIcon: "OL" },
  "ollama-search": { name: "Ollama Search", color: "#ffffff", textIcon: "OL", llm: false },
  "openai": { name: "OpenAI", color: "#10A37F", textIcon: "OA" },
  "opencode": { name: "OpenCode Free", color: "#E87040", textIcon: "OC", freeNoAuth: true },
  "opencode-go": { name: "OpenCode Go", color: "#E87040", textIcon: "OC" },
  "opencode-zen": { name: "OpenCode Zen", color: "#E87040", textIcon: "OZ" },
  "openrouter": { name: "OpenRouter", color: "#F97316", textIcon: "OR" },
  "perplexity": { name: "Perplexity", color: "#20808D", textIcon: "PP" },
  "perplexity-agent": { name: "Perplexity Agent", color: "#20808D", textIcon: "PA" },
  "perplexity-web": { name: "Perplexity Web (Pro/Max)", color: "#20808D", textIcon: "PW" },
  "playht": { name: "PlayHT", color: "#00B4D8", textIcon: "PH", llm: false },
  "poolside": { name: "Poolside", color: "#0EA5E9", textIcon: "PS" },
  "qoder": { name: "Qoder", color: "#EC4899" },
  "qoder-cn": { name: "Qoder CN", color: "#EC4899" },
  "recraft": { name: "Recraft", color: "#EC4899", textIcon: "RC", llm: false },
  "runwayml": { name: "Runway ML", color: "#000000", textIcon: "RW", llm: false },
  "sambanova": { name: "SambaNova", color: "#F97316", textIcon: "SN" },
  "sdwebui": { name: "SD WebUI", color: "#FF7043", textIcon: "SD", llm: false },
  "searchapi": { name: "SearchAPI", color: "#0EA5A4", textIcon: "SA", llm: false },
  "searxng": { name: "SearXNG", color: "#3B82F6", textIcon: "SX", llm: false },
  "selfhosted-embedding": { name: "Self-hosted Embedding", color: "#ffffffff", textIcon: "SE", llm: false },
  "selfhosted-stt": { name: "Self-hosted STT", color: "#ffffffff", textIcon: "ST", llm: false },
  "selfhosted-tts": { name: "Self-hosted TTS", color: "#ffffffff", textIcon: "TT", llm: false },
  "serper": { name: "Serper", color: "#4F46E5", textIcon: "SP", llm: false },
  "siliconflow": { name: "SiliconFlow", color: "#5B6EF5", textIcon: "SF" },
  "stability-ai": { name: "Stability AI", color: "#8B5CF6", textIcon: "SA", llm: false },
  "tavily": { name: "Tavily", color: "#5B21B6", textIcon: "TV", llm: false },
  "tencent": { name: "Tencent Hunyuan", color: "#0052D9", textIcon: "HY" },
  "together": { name: "Together AI", color: "#0F6FFF", textIcon: "TG" },
  "tokenharbor": { name: "Token Harbor", color: "#0F766E", textIcon: "TH" },
  "tokenrouter": { name: "TokenRouter", color: "#0EA5E9", textIcon: "TR" },
  "topaz": { name: "Topaz", color: "#059669", textIcon: "TP", llm: false },
  "tortoise": { name: "Tortoise TTS", color: "#7C3AED", textIcon: "TT", llm: false },
  "trae": { name: "Trae", color: "#FF6A00", textIcon: "TR" },
  "venice": { name: "Venice AI", color: "#DC2626", textIcon: "VE" },
  "vercel-ai-gateway": { name: "Vercel AI Gateway", color: "#111827", textIcon: "VG" },
  "vertex": { name: "Vertex AI", color: "#4285F4", textIcon: "VX" },
  "vertex-partner": { name: "Vertex Partner", color: "#34A853", textIcon: "VP" },
  "volcengine-ark": { name: "Volcengine Ark", color: "#1677FF", textIcon: "ARK" },
  "voyage-ai": { name: "Voyage AI", color: "#0EA5E9", textIcon: "VG", llm: false },
  "windsurf": { name: "Windsurf", color: "#14B8A6" },
  "xai": { name: "xAI (Grok)", color: "#1DA1F2", textIcon: "XA" },
  "xiaomi-mimo": { name: "Xiaomi MiMo", color: "#FF6900", textIcon: "XM" },
  "xiaomi-tokenplan": { name: "Xiaomi MiMo (Token Plan)", color: "#FF6700", textIcon: "XT" },
  "xquik": { name: "Xquik", color: "#5C3327", textIcon: "XQ", llm: false },
  "youcom": { name: "You.com Search", color: "#7C3AED", textIcon: "YC", llm: false },
  "zed": { name: "Zed", color: "#A855F7" },
};

export function providerMeta(id: string): ProviderMeta {
  return (
    PROVIDER_META[id.toLowerCase()] ?? {
      name: id,
      color: "#6b7280",
      textIcon: id.slice(0, 2).toUpperCase(),
    }
  );
}
